apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-kube-storage-version-migrator-operator
  name: config
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
data:
  config.yaml: |
    apiVersion: operator.openshift.io/v1
    kind: GenericOperatorConfig
